g1_gazebo:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 1000  

    torso_controller:
        type: effort_controllers/JointPositionController
        joint: torso_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    # left leg Controllers ---------------------------------------
    left_hip_pitch_controller:
        type: effort_controllers/JointPositionController
        joint: left_hip_pitch_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    left_hip_roll_controller:
        type: effort_controllers/JointPositionController
        joint: left_hip_roll_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    left_hip_yaw_controller:
        type: effort_controllers/JointPositionController
        joint: left_hip_yaw_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    left_knee_controller:
        type: effort_controllers/JointPositionController
        joint: left_knee_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    # left_ankle_pitch_controller:
    #    type: effort_controllers/JointPositionController
    #    joint: left_ankle_pitch_joint
    #    pid: {p: 100.0, i: 0.0, d: 5.0}

    # left_ankle_roll_controller:
    #    type: effort_controllers/JointPositionController
    #    joint: left_ankle_roll_joint
    #    pid: {p: 100.0, i: 0.0, d: 5.0}

    # right leg Controllers ---------------------------------------
    right_hip_pitch_controller:
        type: effort_controllers/JointPositionController
        joint: right_hip_pitch_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    right_hip_roll_controller:
        type: effort_controllers/JointPositionController
        joint: right_hip_roll_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    right_hip_yaw_controller:
        type: effort_controllers/JointPositionController
        joint: right_hip_yaw_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    right_knee_controller:
        type: effort_controllers/JointPositionController
        joint: right_knee_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    # right_ankle_pitch_controller:
    #    type: effort_controllers/JointPositionController
    #    joint: right_ankle_pitch_joint
    #    pid: {p: 100.0, i: 0.0, d: 5.0}

    # right_ankle_roll_controller:
    #    type: effort_controllers/JointPositionController
    #    joint: right_ankle_roll_joint
    #    pid: {p: 100.0, i: 0.0, d: 5.0}


    # left arm Controllers ---------------------------------------
    left_shoulder_pitch_controller:
        type: effort_controllers/JointPositionController
        joint: left_shoulder_pitch_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    left_shoulder_roll_controller:
        type: effort_controllers/JointPositionController
        joint: left_shoulder_roll_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    left_shoulder_yaw_controller:
        type: effort_controllers/JointPositionController
        joint: left_shoulder_yaw_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    left_elbow_pitch_controller:
        type: effort_controllers/JointPositionController
        joint: left_elbow_pitch_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    left_elbow_roll_controller:
        type: effort_controllers/JointPositionController
        joint: left_elbow_roll_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    # right arm Controllers ---------------------------------------
    right_shoulder_pitch_controller:
        type: effort_controllers/JointPositionController
        joint: right_shoulder_pitch_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    right_shoulder_roll_controller:
        type: effort_controllers/JointPositionController
        joint: right_shoulder_roll_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    right_shoulder_yaw_controller:
        type: effort_controllers/JointPositionController
        joint: right_shoulder_yaw_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    right_elbow_pitch_controller:
        type: effort_controllers/JointPositionController
        joint: right_elbow_pitch_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    right_elbow_roll_controller:
        type: effort_controllers/JointPositionController
        joint: right_elbow_roll_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    # Controladores de trayectoria para las piernas
    left_leg_trajectory_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            - left_hip_pitch_joint
            - left_hip_roll_joint
            - left_hip_yaw_joint
            - left_knee_joint
            # - left_ankle_pitch_joint  # Comentar o eliminar
            # - left_ankle_roll_joint   # Comentar o eliminar
        gains:
            left_hip_pitch_joint: {p: 100.0, i: 0.0, d: 5.0}
            left_hip_roll_joint: {p: 100.0, i: 0.0, d: 5.0}
            left_hip_yaw_joint: {p: 100.0, i: 0.0, d: 5.0}
            left_knee_joint: {p: 100.0, i: 0.0, d: 5.0}
            # left_ankle_pitch_joint: {p: 100.0, i: 0.0, d: 5.0}  # Comentar o eliminar
            # left_ankle_roll_joint: {p: 100.0, i: 0.0, d: 5.0}   # Comentar o eliminar
        constraints:
            goal_time: 0.6
            stopped_velocity_tolerance: 0.05
        stop_trajectory_duration: 0.5
        state_publish_rate: 25
        action_monitor_rate: 10

    right_leg_trajectory_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            - right_hip_pitch_joint
            - right_hip_roll_joint
            - right_hip_yaw_joint
            - right_knee_joint
            # - right_ankle_pitch_joint  # Comentar o eliminar
            # - right_ankle_roll_joint   # Comentar o eliminar
        gains:
            right_hip_pitch_joint: {p: 100.0, i: 0.0, d: 5.0}
            right_hip_roll_joint: {p: 100.0, i: 0.0, d: 5.0}
            right_hip_yaw_joint: {p: 100.0, i: 0.0, d: 5.0}
            right_knee_joint: {p: 100.0, i: 0.0, d: 5.0}
            # right_ankle_pitch_joint: {p: 100.0, i: 0.0, d: 5.0}  # Comentar o eliminar
            # right_ankle_roll_joint: {p: 100.0, i: 0.0, d: 5.0}   # Comentar o eliminar
        constraints:
            goal_time: 0.6
            stopped_velocity_tolerance: 0.05
        stop_trajectory_duration: 0.5
        state_publish_rate: 25
        action_monitor_rate: 10

    # Controladores de trayectoria para los brazos
    left_arm_trajectory_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            - left_shoulder_pitch_joint
            - left_shoulder_roll_joint
            - left_shoulder_yaw_joint
            - left_elbow_pitch_joint
            - left_elbow_roll_joint
        gains:
            left_shoulder_pitch_joint: {p: 100.0, i: 0.0, d: 5.0}
            left_shoulder_roll_joint: {p: 100.0, i: 0.0, d: 5.0}
            left_shoulder_yaw_joint: {p: 100.0, i: 0.0, d: 5.0}
            left_elbow_pitch_joint: {p: 100.0, i: 0.0, d: 5.0}
            left_elbow_roll_joint: {p: 100.0, i: 0.0, d: 5.0}
        constraints:
            goal_time: 0.6
            stopped_velocity_tolerance: 0.05
        stop_trajectory_duration: 0.5
        state_publish_rate: 25
        action_monitor_rate: 10

    right_arm_trajectory_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            - right_shoulder_pitch_joint
            - right_shoulder_roll_joint
            - right_shoulder_yaw_joint
            - right_elbow_pitch_joint
            - right_elbow_roll_joint
        gains:
            right_shoulder_pitch_joint: {p: 100.0, i: 0.0, d: 5.0}
            right_shoulder_roll_joint: {p: 100.0, i: 0.0, d: 5.0}
            right_shoulder_yaw_joint: {p: 100.0, i: 0.0, d: 5.0}
            right_elbow_pitch_joint: {p: 100.0, i: 0.0, d: 5.0}
            right_elbow_roll_joint: {p: 100.0, i: 0.0, d: 5.0}
        constraints:
            goal_time: 0.6
            stopped_velocity_tolerance: 0.05
        stop_trajectory_duration: 0.5
        state_publish_rate: 25
        action_monitor_rate: 10